#HDMI
#Clock
set_property PACKAGE_PIN L16 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS25 [get_ports hdmi_clk]
#Data
set_property PACKAGE_PIN AB21 [get_ports vid_data_0[0]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[0]]
set_property PACKAGE_PIN AA21 [get_ports vid_data_0[1]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[1]]
set_property PACKAGE_PIN AB22 [get_ports vid_data_0[2]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[2]]
set_property PACKAGE_PIN AA22 [get_ports vid_data_0[3]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[3]]
set_property PACKAGE_PIN V19 [get_ports vid_data_0[4]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[4]]
set_property PACKAGE_PIN V18 [get_ports vid_data_0[5]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[5]]
set_property PACKAGE_PIN V20 [get_ports vid_data_0[6]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[6]]
set_property PACKAGE_PIN U20 [get_ports vid_data_0[7]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[7]]
set_property PACKAGE_PIN W21 [get_ports vid_data_0[8]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[8]]
set_property PACKAGE_PIN W20 [get_ports vid_data_0[9]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[9]]
set_property PACKAGE_PIN W18 [get_ports vid_data_0[10]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[10]]
set_property PACKAGE_PIN T19 [get_ports vid_data_0[11]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[11]]
set_property PACKAGE_PIN U19 [get_ports vid_data_0[12]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[12]]
set_property PACKAGE_PIN R19 [get_ports vid_data_0[13]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[13]]
set_property PACKAGE_PIN T17 [get_ports vid_data_0[14]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[14]]
set_property PACKAGE_PIN T16 [get_ports vid_data_0[15]]
set_property IOSTANDARD LVCMOS25 [get_ports vid_data_0[15]]
#video active
set_property PACKAGE_PIN T18 [get_ports vid_active_video_0]
set_property IOSTANDARD LVCMOS25 [get_ports vid_active_video_0]
#Sync signals
set_property PACKAGE_PIN R18 [get_ports vid_hsync_0]
set_property IOSTANDARD LVCMOS25 [get_ports vid_hsync_0]
set_property PACKAGE_PIN H15 [get_ports vid_vsync_0]
set_property IOSTANDARD LVCMOS25 [get_ports vid_vsync_0]

#Locked signal -> DS19
set_property PACKAGE_PIN E15 [get_ports vid_locked]
set_property IOSTANDARD LVCMOS25 [get_ports vid_locked] 